### ISSUE TITLE
Source distribution link does not work!

### ISSUE THREAD

**Issue by nukoseer** [NicolBolas/NicolBolas.github.io#1]
I was about to start this book but I realised source distribution link (https://bitbucket.org/alfonse/gltut/downloads/) doesn't work on the Building the Tutorials page. I don't know if this book is still viable but looks like it is and I just want to look at it. I will be very glad if you can refresh the link.

**Comment by excalamus** [comment]
Looks like it was saved by archive.org: https://web.archive.org/web/20200701002741/https://bitbucket.org/alfonse/gltut/downloads/

It may take a moment to download; at first it looks like an error, but it does a redirect to AWS storage.

**Comment by nukoseer** [comment]
I found in this page: https://github.com/paroj/gltut/releases
